insert into "teams" ("teamId", "countryName", "countryFlag", "coach", "fifaRank", "websiteLink", "prevWC", "fifthGame", "fourthGame", "thirdGame", "secondGame", "firstGame", "group")
values (1, 'Qatar', '/images/flags/qatar.png', 'Félix Sánchez', 48, 'https://www.qfa.qa/', 'N/A', 'd', 'd', 'd', 'w', 'd', 'A'),
       (2, 'Ecuador', '/images/flags/ecuador.png', 'Gustavo Alfaro', 44, 'https://www.fef.ec/la-tri/', 'N/A', 'l', 'd', 'w', 'd', 'w', 'A'),
       (3, 'Senegal', '/images/flags/senegal.png', 'Aliou Cissé', 18, 'http://www.fsfoot.sn/', 'Group Stage', 'w', 'w', 'd', 'l', 'w', 'A'),
       (4, 'Netherlands', '/images/flags/netherlands.png', 'Louis van Gaal', 8, 'https://www.knvb.com/dutch-football/', 'N/A', 'd', 'w', 'w', 'd', 'w', 'A'),
       (5, 'England', '/images/flags/england.png', 'Gareth Southgate', 5, 'https://www.englandfootball.com/england/mens-senior-team', '4th Place', 'w', 'l', 'd', 'd', 'l', 'B'),
       (6, 'Iran', '/images/flags/iran.png', 'Carlos Queiroz', 22, 'http://ffiri.ir/en', 'Group Stage', 'w', 'w', 'l', 'w', 'l', 'B'),
       (7, 'USA', '/images/flags/usa.png', 'Gregg Berhalter', 14, 'https://www.ussoccer.com/teams/usmnt', 'N/A', 'l', 'w', 'd', 'w', 'd', 'B'),
       (8, 'Wales', '/images/flags/wales.png', 'Rob Page', 19, 'https://www.faw.cymru/en/', 'N/A', 'l', 'w', 'l', 'd', 'l', 'B'),
       (9, 'Argentina', '/images/flags/argentina.png', 'Lionel Scaloni', 3, 'https://www.afa.com.ar/es/', 'Round of 16', 'w', 'w', 'd', 'w', 'w', 'C'),
       (10, 'Saudi Arabia', '/images/flags/saudi-arabia.png', 'Hervé Renard', 53, 'https://www.saff.com.sa/en/', 'Group Stage', 'l', 'w', 'd', 'l', 'l', 'C'),
       (11, 'Mexico', '/images/flags/mexico.png', 'Gerardo Martino', 12, 'https://fmf.mx/', 'Round of 16', 'l', 'd', 'w', 'd', 'l', 'C'),
       (12, 'Poland', '/images/flags/poland.png', 'Czesław Michniewicz', 26, 'https://pzpn.pl/en', 'Group Stage', 'w', 'w', 'l', 'd', 'l', 'C'),
       (13, 'France', '/images/flags/france.png', 'Didier Deschamp', 4, 'https://uk.fff.fr/', 'Winner', 'w', 'l', 'd', 'd', 'l', 'D'),
       (14, 'Australia', '/images/flags/australia.png', 'Graham Arnold', 39, 'https://www.footballaustralia.com.au/', 'N/A', 'w', 'w', 'w', 'l', 'w', 'D'),
       (15, 'Denmark', '/images/flags/denmark.png', 'Kasper Hjulmand', 10, 'https://www.dbu.dk/', 'Round of 16', 'w', 'w', 'w', 'l', 'w', 'D'),
       (16, 'Tunisia', '/images/flags/tunisia.png', 'Jalel Kadri', 30, 'https://www.ftf.org.tn/fr/', 'Group Stage', 'd', 'w', 'd', 'w', 'w', 'D'),
       (17, 'Spain', '/images/flags/spain.png', 'Luis Enrique', 6, 'https://www.rfef.es/es', 'Round of 16', 'w', 'd', 'd', 'w', 'w', 'E'),
       (18, 'Costa Rica', '/images/flags/costa-rica.png', 'Luis Fernando Suarez', 34, 'https://www.fedefutbol.com/', 'Group Stage', 'w', 'w', 'l', 'w', 'w', 'E'),
       (19, 'Germany', '/images/flags/germany.png', 'Hansi Flick', 11, 'https://www.dfb.de/en/en-start/', 'Group Stage', 'd', 'd', 'd', 'd', 'w', 'E'),
       (20, 'Japan', '/images/flags/japan.png', 'Hejime Moriyasu', 24, 'http://www.jfa.jp/eng/', 'Round of 16', 'w', 'l', 'w', 'd', 'w', 'E'),
       (21, 'Belgium', '/images/flags/belgium.png', 'Roberto Martinez', 2, 'https://www.rbfa.be/', '3rd Place', 'w', 'l', 'w', 'd', 'w', 'F'),
       (22, 'Canada', '/images/flags/canada.png', 'John Herdman', 43, 'https://canadasoccer.com/', 'N/A', 'l', 'd', 'l', 'd', 'l', 'F'),
       (23, 'Morocco', '/images/flags/morocco.png', 'Walid Regragui', 23, 'https://www.cafonline.com/member-associations/mar/', 'Group Stage', 'd', 'w', 'l', 'w', 'w', 'F'),
       (24, 'Croatia', '/images/flags/croatia.png', 'Zlatko Dalić', 15, 'https://hns-cff.hr/en/', '2nd Place', 'w', 'l', 'd', 'w', 'w', 'F'),
       (25, 'Brazil', '/images/flags/brazil.png', 'Tite', 1, 'https://www.cbf.com.br/', 'Quarter Finals', 'w', 'w', 'w', 'w', 'w', 'G'),
       (26, 'Serbia', '/images/flags/serbia.png', 'Dragan Stojković', 25, 'www.fss.rs/', 'Group Stage', 'l', 'l', 'w', 'l', 'd', 'G'),
       (27, 'Switzerland', '/images/flags/switzerland.png', 'Murat Yakin', 16, 'www.football.ch', 'Round of 16', 'd', 'l', 'l', 'l', 'w', 'G'),
       (28, 'Cameroon', '/images/flags/cameroon.png', 'Rigobert Song', 38, 'www.fecafoot-officiel.com', 'N/A', 'w', 'l', 'w', 'l', 'w', 'G'),
       (29, 'Portugal', '/images/flags/portugal.png', 'Fernando Santos', 9, 'https://www.cbf.com.br/', 'Round of 16', 'w', 'w', 'w', 'w', 'w', 'H'),
       (30, 'Ghana', '/images/flags/ghana.png', 'Otto Addo', 60, 'https://www.ghanafa.org/', 'N/A', 'd', 'w', 'd', 'l', 'w', 'H'),
       (31, 'Uruguay', '/images/flags/Uruguay.png', 'Diego Alonso', 13, 'https://www.auf.org.uy/', 'Quarter Finals', 'w', 'w', 'w', 'd', 'w', 'H'),
       (32, 'South Korea', '/images/flags/korea-republic.png', 'Paulo Bento', 28, 'https://www.kfa.or.kr/', 'Group Stage', 'd', 'w', 'w', 'w', 'l', 'H');
